trigger: none
pr: none

variables:
  - group: terraform-secrets

stages:
# 1. Terraform IaC
- stage: iac
  displayName: 'Provision Infra with Terraform'
  jobs:
  - job: terraform
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.7.5'

    - script: |
        terraform -version
        cd iac/terraform
        terraform init
        terraform apply \
          -auto-approve \
          -var="prefix=webdemo" \
          -var="subscription_id=$(ARM_SUBSCRIPTION_ID)" \
          -var="tenant_id=$(ARM_TENANT_ID)" \
          -var="client_id=$(ARM_CLIENT_ID)" \
          -var="client_secret=$(ARM_CLIENT_SECRET)"
      displayName: "Terraform Init & Apply"
      env:
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)

# 2. Deploy to Dev
- stage: Dev
  dependsOn: iac
  jobs:
  - deployment: DeployDev
    environment: 'Dev'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'az-spn-one'
              appName: 'webdemo-app'
              package: '$(System.DefaultWorkingDirectory)/src/bin/Release/net8.0/publish'

# 3. Staging
- stage: Staging
  dependsOn: Dev
  jobs:
  - deployment: DeployStaging
    environment: 'Staging'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'az-spn-one'
              appName: 'webdemo-app'
              package: '$(System.DefaultWorkingDirectory)/src/bin/Release/net8.0/publish'

# 4. Prod (manual approval if set in Environments)
- stage: Prod
  dependsOn: Staging
  jobs:
  - deployment: DeployProd
    environment: 'Prod'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureWebApp@1
            inputs:
              azure