trigger: none
pr: none

stages:
# 1. Terraform IaC
- stage: iac
  displayName: 'Provision Infra with Terraform'
  jobs:
  - job: terraform
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.7.5'

    - script: |
        terraform -version
        cd iac/terraform
        terraform init
        terraform apply -auto-approve -var="prefix=webdemo"
      displayName: "Terraform Init & Apply"

# 2. Deploy to Dev
- stage: Dev
  dependsOn: iac
  jobs:
  - deployment: DeployDev
    environment: 'Dev'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'az-spn-one'
              appName: 'webdemo-app'
              package: '$(System.DefaultWorkingDirectory)/src/bin/Release/net8.0/publish'

# 3. Staging
- stage: Staging
  dependsOn: Dev
  jobs:
  - deployment: DeployStaging
    environment: 'Staging'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'az-spn-one'
              appName: 'webdemo-app'
              package: '$(System.DefaultWorkingDirectory)/src/bin/Release/net8.0/publish'

# 4. Prod (manual approval if set in Environments)
- stage: Prod
  dependsOn: Staging
  jobs:
  - deployment: DeployProd
    environment: 'Prod'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'az-spn-one'
              appName: 'webdemo-app'
              package: '$(System.DefaultWorkingDirectory)/src/bin/Release/net8.0/publish'