trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    version: '8.x'

- script: |
    cd src
    dotnet restore
    dotnet build --configuration $(buildConfiguration) --no-restore
    dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish
    cd ../tests
    dotnet test --logger trx
  displayName: 'Restore, Build, Publish, Test'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'