trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    version: '8.x'

- script: |
    cd src
    dotnet restore
    dotnet build --configuration Release --no-restore
    dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)/publish
    cd ../tests
    dotnet test --logger trx
  displayName: 'Restore, Build, Test, Publish'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/publish'
    ArtifactName: drop